name: operation_translate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_tts: ^4.2.2
  google_generative_ai: ^0.4.6
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path: 'assets/icon.png'
  ios: true

flutter:
  assets:
    - assets/negative.png
  uses-material-design: true
